- hosts: 127.0.0.1
  connection: local

  roles:
    - role: cluster
    - role: nexus
    - role: jenkins
    - role: loki
    - role: alloy
    - role: prometheus
    - role: grafana
    - role: ingress