- name: Add Ingress Helm repo
  kubernetes.core.helm_repository:
      name: ingress-nginx
      #force_update: true
      repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx  Helm Chart
  kubernetes.core.helm:
      name: ingress-nginx
      release_namespace: '{{ k8s_namespace.build }}'
      create_namespace: true
      chart_ref: ingress-nginx/ingress-nginx
      wait: true

- name: Creating Ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: webapp-ingress
        namespace: '{{ k8s_namespace.build }}'
      spec:
        ingressClassName: nginx
        rules:
          - host: '{{ jenkins.host }}'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: '{{ jenkins.service_name }}'
                      port:
                        number: '{{ jenkins.port }}'
          - host: '{{ grafana.host }}'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: '{{ grafana.service_name }}'
                      port:
                        number: '{{ grafana.port }}'
          - host: '{{ nexus.host }}'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: '{{ nexus.service_name }}'
                      port:
                        number: '{{ nexus.port }}'
          - host: '{{ sonarqube.host }}'
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: '{{ sonarqube.service_name }}'
                      port:
                        number: '{{ sonarqube.port }}'