- name: Search for Jenkins Pod
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: '{{ k8s_namespace.build }}'
    label_selectors:
      - app.kubernetes.io/name = jenkins
      - app.kubernetes.io/instance = {{ jenkins.service_name }}
  register: jenkins_pod

- name: Get Jenkins admin password
  kubernetes.core.k8s_exec:
    namespace: '{{ k8s_namespace.build }}'
    pod: '{{ jenkins_pod.resources[0].metadata.name }}'
    command: /bin/cat /run/secrets/additional/chart-admin-password
  register: jenkins_admin_password

- name: Print Jenkins credentials
  debug:
    msg: "Jenkins URL: http://{{ jenkins.host }}{{ jenkins.path }} | admin password: {{ jenkins_admin_password.stdout }}"
