- name: Add Jenkins Helm repo
  kubernetes.core.helm_repository:
      name: jenkins
      #force_update: true
      repo_url: https://charts.jenkins.io

- name: Install Jenkins Helm Chart
  kubernetes.core.helm:
      name: '{{ jenkins.service_name }}'
      release_namespace: '{{ k8s_namespace.build }}'
      chart_ref: jenkins/jenkins
      wait: true
      values:
        controller:
          jenkinsUriPrefix: '{{ jenkins.path }}'
          installPlugins: # base plugins should be specified when using this entry
            - kubernetes
            - git
            - configuration-as-code
            - workflow-multibranch
            - workflow-aggregator
            - job-dsl # added to persist jobs
          JCasC:
            configScripts:
              welcome-message: |
                jenkins:
                  systemMessage: Welcome to k8s-cicd
              scheduler-job: |
                jobs:
                  - script: >
                      multibranchPipelineJob('scheduler') {
                          branchSources {
                              git {
                                  id('scheduler')
                                  remote('https://github.com/erwanjouan/test-tool-backend.git')
                              }
                          }
                          factory {
                            workflowBranchProjectFactory {
                                scriptPath('cicd/Jenkinsfile')
                            }
                          }
                      }
